services:
  php:
    build:
      context: ./docker/php
      dockerfile: php.dockerfile
    container_name: singelo_php
    ports:
      - "9000:9000"
    volumes:
      - ./docker/php/php-custom.ini:/usr/local/etc/php/conf.d/php-custom.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./project:/var/www/project
    networks:
      - singelo_network

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: nginx.dockerfile
    container_name: singelo_nginx
    ports:
      - "8000:8000"
    volumes:
      - ./project:/var/www/project
      - ./docker/nginx/servers:/etc/nginx/conf.d/servers
    depends_on:
      - php
    networks:
      - singelo_network

  rabbitmq:
    build:
      context: ./docker/rabbitmq
      dockerfile: rabbitmq.dockerfile
    container_name: singelo_rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - singelo_network

networks:
  singelo_network:
