services:
  php:
    build:
      context: ./docker/php
      dockerfile: php.dockerfile
    container_name: singelo_php
    ports:
      - "9000:9000"
    volumes:
      - ./docker/php/php-custom.ini:/usr/local/etc/php/conf.d/php-custom.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./project:/var/www/project
    networks:
      - network

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: nginx.dockerfile
    container_name: singelo_nginx
    ports:
      - "8000:8000"
    volumes:
      - ./project:/var/www/project
      - ./docker/nginx/servers:/etc/nginx/conf.d/servers
    depends_on:
      - php
    networks:
      - network

  rabbitmq:
    build:
      context: ./docker/rabbitmq
      dockerfile: rabbitmq.dockerfile
    container_name: singelo_rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - network

  postgres:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - network

volumes:
  postgres_data:

networks:
  network:
